spring.application.name=dbase

spring.datasource.primary.jdbc-url=${SPRING_DATASOURCE_PRIMARY_JDBC_URL:jdbc:postgresql://localhost:5432/dbase}
spring.datasource.primary.username=${SPRING_DATASOURCE_PRIMARY_USERNAME:postgres}
spring.datasource.primary.password=${SPRING_DATASOURCE_PRIMARY_PASSWORD:admin}

spring.datasource.secondary.jdbc-url=${SPRING_DATASOURCE_SECONDARY_JDBC_URL:jdbc:postgresql://ep-dark-hall-agjare52-pooler.c-2.eu-central-1.aws.neon.tech/backup_db?user=neondb_owner&password=npg_0tTSrjDAxwg4&sslmode=require&channelBinding=require}
spring.datasource.secondary.username=${SPRING_DATASOURCE_SECONDARY_USERNAME:neondb_owner}
spring.datasource.secondary.password=${SPRING_DATASOURCE_SECONDARY_PASSWORD:npg_0tTSrjDAxwg4}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.messages.basename=messages
spring.messages.encoding=UTF-8

server.port=8180


spring.datasource.secondary.connection-timeout=10000
spring.datasource.secondary.keepalive-time=30000
spring.datasource.secondary.maximum-pool-size=2
spring.datasource.secondary.minimum-idle=0
spring.datasource.secondary.idle-timeout=60000